apiVersion: v2
name: glowroot
description: Helm chart for glowroot
type: application
version: 1.0.9
appVersion: 0.14.0-beta.3
icon: https://glowroot.org/images/favicon-440x440.22b5b3f3.png

maintainers:
  - name: Lucas Hahn 
    email: lucas.hahn@novum-rgi.de

dependencies:
- name: cassandra
  repository: https://charts.bitnami.com/bitnami
  version: 9.1.18
  condition: cassandra.enabled